data:
  batch_size: 64
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: /mnt/tuyenld/data/endoscopy/
  num_workers: 6
  pin_mem: true
  root_path: /mnt/quanhd/endoscopy/pretrain.json
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
  image_resize: false
logging:
  folder: /mnt/quanhd/ijepa_stable/logs_rgst/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: "/mnt/quanhd/ijepa_stable/logs_rgst/jepa-ep150.pth.tar"
  use_bfloat16: true
  use_register: true
  num_registers: 4
  type_embed: conv
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 600
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 8
  lr: 0.001
  start_lr: 0.0002
  warmup: 80
  weight_decay: 0.04